### ISSUE TITLE
Add MySQL config files

### ISSUE THREAD

**Issue by Kourchenko** [Hack4Eugene/speedupamerica-frontend#11]
Implement database client (must support connection retry and pooling).
Create a new file in `src/mysql/` that implements a class with helper functions to form a connection. Will need to export class to be used in other classes (such as Submission class) to create a query. 
Let Docker handle `host, user, password, database, etc.`

**NodeJS and MySQL**
 https://github.com/mysqljs/mysql
`npm install mysql`

**Comment by ryanrolds** [comment]
Make sure to use a single client with a connection pool of no more than 6 connections (we don't want to hit the connection limit on the server when we have multiple instances and during upgrades, which runs 2x the number of instances). 

Implement a test endpoint that reads from one of the DB. Make sure the query works, stop the MySQL container, make sure the queries fail, restart the container and confirm the queries work without restarting the frontend service.

**Comment by ryanrolds** [comment]
Make sure the disconnect and reconnect events write notices to the logs.
