### ISSUE TITLE
Setup config and logging (1SP)

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/speedupamerica-frontend#2]
* Implement a config module `src/config.ts` that provides helper functions for getting at environment variables
    * ENV (string) default: development
    * PORT (integer) default: 8080
* Add the latest version of Winston to the project
* Create logging modules `src/logging.ts` and have a helper that returns a singleton instance of the logger configured to write JSON formatted logs to STDOUT. Also, include in log message:
    * environmen=value of ENV
    * timestamp=ISO8601 datetime down to millisecond with UTC TZ
    * level
    * type=application
* Configure the logger to write debug level for development env and for non-development write info level 
* Update `src/main.ts` and have it write "starting" and "stopping".

**Comment by Kourchenko** [comment]
7/18 - Completed and merged. Using Winston and Loggly.
