### ISSUE TITLE
Add 'robot.txt' (0.5 SP)

### ISSUE THREAD

**Issue by Kourchenko** [Hack4Eugene/speedupamerica-frontend#20]
Add "robots.txt" file to `src/view/`.
Include denys all and noindex meta tags.

Helpful Documentation
https://support.google.com/webmasters/answer/6062596?hl=en&ref_topic=6061961

**Comment by Kourchenko** [comment]
1. Create` src/view/` folder - where all our HTML pages will live
2. Create "robots.txt"
3. Create `index.html` and add script to check if in dev/test environment - if yes add meta tag for robots file.
https://www.searchenginejournal.com/best-practices-setting-meta-robots-tags-robots-txt/188655/#close

**Comment by ryanrolds** [comment]
If the env is production we will want to allow all and not have the noindex header/meta tags.

**Comment by Kourchenko** [comment]
Unassigning myself. We will complete this when we implement a template engine ([PUG](https://pugjs.org/api/getting-started.html)) and can render HTML pages server-side.
